services:
  terrapanel:
    image: "ghcr.io/lumidust/terrapanel:latest"
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
      - "7777:7777"
    volumes:
      - "./data:/data"
